# Build stage
FROM node:22-bookworm-slim AS builder

WORKDIR /app

# Copy package files first for layer caching
COPY package*.json ./

# Node 22 Alpine currently ships npm 10, whose workspace/optional-dependency
# resolver rejects the lockfile generated by the repository's npm 11 toolchain.
# Pin the same npm major in both stages so image builds are reproducible.
RUN npm install --global npm@11.12.1 && npm ci

# Copy source
COPY tsconfig.json ./
COPY drizzle.config.ts ./
COPY src/ ./src/

# Build TypeScript
RUN npm run build

# Production stage
FROM node:22-bookworm-slim AS production

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install production dependencies only
# The production image contains only the gateway package. The frontend is a
# separate workspace and is intentionally excluded from this backend image.
RUN npm install --global npm@11.12.1 && \
    npm ci --omit=dev --workspaces=false && \
    npm cache clean --force

# Copy built output from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/drizzle.config.ts ./

# Copy migration files
COPY src/db/migrations ./dist/db/migrations

# Non-root user
RUN groupadd --system --gid 1001 appgroup && \
    useradd --system --uid 1001 --gid appgroup --no-create-home \
      --shell /usr/sbin/nologin appuser

USER appuser

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:3000/health').then((response) => process.exit(response.ok ? 0 : 1)).catch(() => process.exit(1))"

CMD ["node", "dist/index.js"]
