/**
 * Graph data types for the custom PostgreSQL + pgvector graph store.
 *
 * These interfaces mirror the rows in `graph_nodes`, `graph_edges`, and
 * `agent_episodes` tables (see `src/db/schema/tables.ts`) but use a
 * domain-friendly shape: camelCase fields, optional `id` (assigned on
 * insert), optional `embedding` (generated by `src/shared/embeddings.ts`
 * if not provided), and a typed `properties` / `metadata` bag.
 */

/**
 * A knowledge-graph node representing an entity inside a simulation
 * (state actor, faction, location, event, etc.).
 *
 * Uniqueness is enforced at the DB level via the composite constraint
 * `uq_graph_nodes_sim_entity` on `(simulation_id, entity_id)` — callers
 * should use `entityId` as a stable identifier (e.g. the slugged entity
 * name from the source SimPackage).
 */
export interface GraphNode {
  /** Database-assigned UUID — absent until the row has been inserted. */
  id?: string;
  /** Owning tenant — propagated from the simulation for tenant isolation. */
  tenantId: string;
  /** Simulation this node belongs to. */
  simulationId: string;
  /** Stable external identifier (e.g. entity slug). */
  entityId: string;
  /** Ontology class (e.g. `StateActor`, `Faction`, `Location`). */
  entityType: string;
  /** Human-readable display name used for search and UI. */
  name: string;
  /** Arbitrary per-node attributes (stance, objectives, etc.). */
  properties?: Record<string, unknown>;
  /** 384-dimension embedding — generated from `name` if omitted. */
  embedding?: number[];
}

/**
 * A directed edge describing a relationship between two graph nodes.
 *
 * `weight` is a 0–1 influence score used by the MiroFish swarm to
 * amplify or dampen message passing along the edge.
 */
export interface GraphEdge {
  id?: string;
  tenantId: string;
  simulationId: string;
  /** UUID of the source `GraphNode` (FK → `graph_nodes.id`). */
  sourceNodeId: string;
  /** UUID of the target `GraphNode` (FK → `graph_nodes.id`). */
  targetNodeId: string;
  /** Relationship label (e.g. `ALLIED_WITH`, `OPPOSES`, `COMMANDS`). */
  edgeType: string;
  /** Arbitrary edge attributes. */
  properties?: Record<string, unknown>;
  /** Influence weight, 0–1, stored as a decimal. Defaults to 1.0. */
  weight?: number;
}

/**
 * A single memory entry for an agent at a given simulation round.
 *
 * Episodes are append-only and used for semantic retrieval during
 * later rounds — the `embedding` is searched via pgvector cosine
 * distance to surface relevant context.
 */
export interface AgentEpisode {
  id?: string;
  tenantId: string;
  simulationId: string;
  /** OASIS agent ID (integer from the generated profile CSV). */
  agentId: number;
  /** Round number this episode was captured in (1-indexed). */
  roundNumber: number;
  /** Action category (e.g. `post`, `reply`, `observe`, `decide`). */
  actionType: string;
  /** Free-form text content used for embedding + search. */
  content: string;
  /** 384-dimension embedding — generated from `content` if omitted. */
  embedding?: number[];
  /** Arbitrary structured metadata (target, sentiment, faction, etc.). */
  metadata?: Record<string, unknown>;
}

/**
 * Result shape for `searchEpisodes` — an `AgentEpisode` augmented with
 * the cosine similarity score (0–1) against the query embedding.
 * Higher is more similar.
 */
export interface EpisodeSearchResult extends AgentEpisode {
  /** Cosine similarity score in [0, 1]. */
  similarity: number;
}
